"""
Adverse-action notices (ECOA / Regulation B).

When credit is declined, the applicant must be told the *specific principal
reasons* — not a generic refusal. This module turns a recorded decision and its
SHAP contributions into that statement of reasons.

The wording here is illustrative for a prototype. A real deployment must have
its notice text, creditor details and agency address reviewed by counsel.
"""

from datetime import datetime, timezone

# Regulation B expects the principal reasons, conventionally up to four.
MAX_PRINCIPAL_REASONS = 4

# Model feature -> the reason phrasing an applicant actually receives.
ADVERSE_REASONS = {
    "payment_consistency_pct": "History of missed or late payments",
    "income_volatility_score": "Income is irregular or difficult to verify",
    "debt_trend": "Level of debt has been increasing",
    "credit_score": "Credit score is below our requirement for this product",
    "income": "Income is insufficient for the amount requested",
    "existing_debt": "Existing debt obligations are too high",
    "loan_amount": "Amount requested is too high relative to your profile",
}

# What the applicant can do about each reason — not required, but it is the
# difference between a notice that informs and one that merely complies.
REMEDIES = {
    "payment_consistency_pct": "Making the next 6–12 payments on time will improve this.",
    "income_volatility_score": "Providing additional proof of income may help.",
    "debt_trend": "Reducing outstanding balances will improve this.",
    "credit_score": "You may request a free copy of your credit report.",
    "income": "You may reapply with a co-applicant or a lower amount.",
    "existing_debt": "Paying down existing balances will improve this.",
    "loan_amount": "You may reapply for a smaller amount.",
}

CREDITOR_NAME = "Credit Risk Decision Engine (Demonstration Lender)"


def principal_reasons(shap: dict, limit=MAX_PRINCIPAL_REASONS) -> list[dict]:
    """
    The factors that most increased this applicant's risk, worst first.

    Only positive SHAP contributions count — those are the features that pushed
    risk *up* and therefore drove the denial. Factors that helped the applicant
    are irrelevant to a statement of adverse reasons.
    """
    adverse = [(k, v) for k, v in (shap or {}).items() if v > 0]
    adverse.sort(key=lambda kv: kv[1], reverse=True)
    return [
        {
            "code": k,
            "reason": ADVERSE_REASONS.get(k, k.replace("_", " ").capitalize()),
            "what_you_can_do": REMEDIES.get(k, ""),
            "impact_pct": round(v, 2),
        }
        for k, v in adverse[:limit]
    ]


def build_notice(decision: dict) -> dict:
    """Assemble a complete adverse-action notice from a recorded decision."""
    reasons = principal_reasons(decision.get("shap", {}))
    decided_at = decision.get("created_at") or datetime.now(timezone.utc).isoformat()

    return {
        "decision_id": decision.get("id"),
        "applicant_id": decision.get("applicant_id"),
        "creditor": CREDITOR_NAME,
        "date": decided_at,
        "action_taken": "Credit application declined",
        "principal_reasons": reasons,
        # Reg B §1002.9(b)(2) — the score disclosure when a score was used.
        "score_disclosure": {
            "used": True,
            "risk_score_pct": decision.get("risk"),
            "scale": "0–100, where a higher figure indicates greater risk of missed payments",
            "model": decision.get("model_version", ""),
        },
        "ecoa_notice": (
            "The federal Equal Credit Opportunity Act prohibits creditors from "
            "discriminating against credit applicants on the basis of race, colour, "
            "religion, national origin, sex, marital status, age (provided the applicant "
            "has the capacity to enter into a binding contract); because all or part of "
            "the applicant's income derives from any public assistance programme; or "
            "because the applicant has in good faith exercised any right under the "
            "Consumer Credit Protection Act."
        ),
        "appeal_rights": (
            "If you believe this decision is incorrect, you may request a review and "
            "submit supporting documentation within 60 days."
        ),
        "reviewed_by": decision.get("reviewed_by", ""),
        "disclaimer": (
            "PROTOTYPE — generated by a demonstration system trained on synthetic data. "
            "Not a valid lending decision or legal notice."
        ),
    }
